# docker-compose.yml
version: "3"
services:
  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app/backend
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]