# This is the version of the Docker Compose file format.
version: "3"

# Define the services that make up your application.
services:
  # Service named 'app' represents your application container.
  app:
    # Load environment variables from the specified .env file.
    env_file:
      - ./.env

    # Build the Docker image for the 'app' service using the current directory as the context.
    # It uses the 'Dockerfile' as the build context.
    build:
      context: .
      dockerfile: Dockerfile

    # Map port 80 from the host to port 80 in the 'app' container.
    ports:
      - "80:80"

    # Mount the current directory as a volume into the '/app/backend' directory in the container.
    volumes:
      - .:/app/backend

    # Specify the command to run within the container when it starts.
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
